#!/usr/bin/env bash
sudo apt install pass

# Command line fuzzy find
if which fzf | grep -qv fzf; then
	git clone https://github.com/junegunn/fzf.git $HOME/personal/fzf
	$HOME/personal/fzf/install
	eval "$(fzf --bash)"
fi
